name: Build and Deploy WordPress Docker Image

on:
  push:
    branches:
      - testing

permissions:
  contents: write

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      semver_tag: ${{ steps.semver.outputs.new_tag }}
      commit_sha: ${{ github.sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate SemVer Tag
      id: semver
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: v
        release_branches: testing

  build:
    runs-on: ubuntu-latest
    needs: versioning
    outputs:
      image_tag: ${{ needs.versioning.outputs.commit_sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: DEBUG
      run: |
        echo "DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}"
        echo "semver_tag=${{ needs.versioning.outputs.semver_tag }}"
        echo "commit_sha=${{ needs.versioning.outputs.commit_sha }}"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        tags: |
          ${{ vars.DOCKER_USERNAME }}/wordpress:${{ needs.versioning.outputs.semver_tag }}
          ${{ vars.DOCKER_USERNAME }}/wordpress:${{ needs.versioning.outputs.commit_sha }}
        push: true
        file: .dockerfile

    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Image build result for ${{ github.repository }}"
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: |
          Result is ${{ job.status }}
          Commit message: ${{ github.event.head_commit.message }}

  update-helm:
    runs-on: ubuntu-latest
    needs: [versioning, build]

    steps:
    - name: Checkout Helm Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ vars.USER_GITHUB }}/${{ vars.HELM_REPO}}
        token: ${{ secrets.TOKEN_GITHUB }}
        path: helm-repo

    - name: Set up Helm
      uses: azure/setup-helm@v4.3.0

    - name: Update Chart Versions
      run: |
        TAG="${{ needs.versioning.outputs.semver_tag }}"
        CLEAN_VERSION="${TAG/v/}"

        sed -i "s/^version: .*/version: $TAG/" helm-repo/helm-sources/wordpress/Chart.yaml
        sed -i "s/^appVersion: .*/appVersion: \"$TAG\"/" helm-repo/helm-sources/wordpress/Chart.yaml

        sed -i "s|tag: \".*\"|tag: \"${{ needs.build.outputs.image_tag }}\"|" helm-repo/helm-sources/wordpress/values.yaml

    - name: Package and Push Chart
      run: |
        cd helm-repo
        helm package helm-sources/wordpress -d helm-releases
        helm repo index --url "${{ vars.URL_HELM_REPO }}" --merge index.yaml .

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update: WordPress ${{ needs.versioning.outputs.semver_tag }}"
        git push

    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Update HELM repository ${{ github.ref_name }}"
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: |
          ${{ job.status }}

  update-argocd:
    runs-on: ubuntu-latest
    needs: update-helm

    steps:
    - name: Checkout ArgoCD repository
      uses: actions/checkout@v4
      with:
        repository: ${{ vars.USER_GITHUB }}/${{ vars.ARGOCD_REPO }}
        token: ${{ secrets.TOKEN_GITHUB }}
        path: argocd-repo

    - name: Update ArgoCD Application
      run: |
        TAG="${{ needs.versioning.outputs.semver_tag }}"
        CLEAN_TAG="${TAG/v/}"

        sed -i "s|version: .*|version: $CLEAN_TAG|" applications/dev/wordpress-dev.yaml

        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update: ArgoCD targets chart version ${CLEAN_TAG}"
        git push

    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Update ArgoCD application ${{ github.ref_name }}"
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: |
          ${{ job.status }}

